// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CTRL_BUS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of thresh
//        bit 31~0 - thresh[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of slope
//        bit 31~0 - slope[31:0] (Read/Write)
// 0x1c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XCOMPRESSOR_CTRL_BUS_ADDR_THRESH_DATA 0x10
#define XCOMPRESSOR_CTRL_BUS_BITS_THRESH_DATA 32
#define XCOMPRESSOR_CTRL_BUS_ADDR_SLOPE_DATA  0x18
#define XCOMPRESSOR_CTRL_BUS_BITS_SLOPE_DATA  32

