// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcompressor.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCompressor_CfgInitialize(XCompressor *InstancePtr, XCompressor_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCompressor_Set_thresh(XCompressor *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCompressor_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCOMPRESSOR_CTRL_BUS_ADDR_THRESH_DATA, Data);
}

u32 XCompressor_Get_thresh(XCompressor *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCompressor_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCOMPRESSOR_CTRL_BUS_ADDR_THRESH_DATA);
    return Data;
}

void XCompressor_Set_slope(XCompressor *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCompressor_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCOMPRESSOR_CTRL_BUS_ADDR_SLOPE_DATA, Data);
}

u32 XCompressor_Get_slope(XCompressor *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCompressor_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCOMPRESSOR_CTRL_BUS_ADDR_SLOPE_DATA);
    return Data;
}

